var nonComHints = [];

const nonComHintsEnum = {
    TOWNHALLBASEMENT1: 0,
    TOWNHALLBASEMENT2: 1,
    TOWNHALLBASEMENT3: 2,
    TOWNHALLTAXOFFICE1: 3,
    TOWNHALLTAXOFFICE2: 4,
    TOWNHALLTAXOFFICE3: 5,
}